default:
  # torch
  gpu: True
  seed: 7

  # env(sim)
  pattern: (5,3)
  rand: False

  # World_model
  capacity: 5000

  # models
  Belief_state_update:
    layers: 1
    node_size: 100
    activation: nn.ELU()

  Transition:
    layers: 1
    node_size: 100
    activation: nn.ELU()

  Observation:
    layers: 1
    node_size: 100
    activation: nn.ELU()

  Reward:
    layers: 1
    node_size: 64
    activation: nn.ELU()

